// <auto-generated />
using System;
using BookStoreServerNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreServerNet.Data.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("BookStoreServerNet.Models.Book", b =>
                {
                    b.Property<long>("Isbn13")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isbn13");

                    b.Property<string>("Authors")
                        .HasColumnType("TEXT")
                        .HasColumnName("authors");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("REAL")
                        .HasColumnName("average_rating");

                    b.Property<string>("Categories")
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Isbn10")
                        .HasColumnType("TEXT")
                        .HasColumnName("isbn10");

                    b.Property<int?>("NumberOfPages")
                        .HasColumnType("INTEGER")
                        .HasColumnName("num_pages");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price");

                    b.Property<int?>("RatingsCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ratings_count");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("subtitle");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("published_year");

                    b.HasKey("Isbn13");

                    b.ToTable("Books", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
